"""Initial database setup for new schema

Revision ID: 4f600fac78f9
Revises: 
Create Date: 2025-07-17 22:25:00.105476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f600fac78f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_replies_received', sa.Integer(), nullable=False),
    sa.Column('total_replies_sent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('group_relations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id', 'group_id', name='_user_group_uc')
    )
    op.create_table('reply_relations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('replier_id', sa.BigInteger(), nullable=False),
    sa.Column('replied_to_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['replied_to_id'], ['group_relations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replier_id'], ['group_relations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('replier_id', 'replied_to_id', name='_replier_replied_to_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_relations')
    op.drop_table('group_relations')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###
