"""Initial database schema

Revision ID: 995907ca01dc
Revises: 
Create Date: 2025-07-16 01:55:14.673954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '995907ca01dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reply_relations', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'reply_relations', ['id'])
    op.alter_column('telegram_users', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_unique_constraint(None, 'telegram_users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_users', type_='unique')
    op.alter_column('telegram_users', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint(None, 'reply_relations', type_='unique')
    op.alter_column('reply_relations', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
