"""Initial database setup

Revision ID: fd345c53ec5d
Revises: 
Create Date: 2025-07-14 17:05:24.137835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd345c53ec5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_relations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('replier_id', sa.BigInteger(), nullable=False),
    sa.Column('replied_to_id', sa.BigInteger(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['replied_to_id'], ['telegram_users.id'], ),
    sa.ForeignKeyConstraint(['replier_id'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('replier_id', 'replied_to_id', name='_replier_replied_to_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_relations')
    # ### end Alembic commands ###
